// data.dart
final List<String> carOptions = [
  'Toyota',
  'Ford',
  'Nissan',
  'Honda',
  'Chevrolet',
  'BMW',
  'Mercedes-Benz',
  'Hyundai',
  'Kia',
  'Volkswagen',
  'Audi',
  'Subaru',
  'Mazda',
  'Lexus',
  'Jeep',
  'Tesla',
  'Dodge',
  'Volvo',
  'Porsche',
  'Peugeot',
  'Renault',
  'Fiat',
  'Citroën',
  'Suzuki',
  'Skoda',
  'Mitsubishi',
  'Land Rover',
  'Jaguar',
];

// Updated Map of car models and their accurate weights
final Map<String, List<Map<String, dynamic>>> modelMap = {
  'Toyota': [
    {'name': 'Camry', 'weight': 1515},
    {'name': 'Corolla', 'weight': 1300},
    {'name': 'Prius', 'weight': 1385},
    {'name': 'RAV4', 'weight': 1650},
    {'name': 'Supra', 'weight': 1520},
    {'name': 'Highlander', 'weight': 2005},
    {'name': 'Tacoma', 'weight': 1900},
  ],
  'Ford': [
    {'name': 'Mustang', 'weight': 1680},
    {'name': 'Fiesta', 'weight': 1160},
    {'name': 'F-150', 'weight': 2250},
    {'name': 'Escape', 'weight': 1600},
    {'name': 'Focus', 'weight': 1375},
    {'name': 'Explorer', 'weight': 2100},
  ],
  'Nissan': [
    {'name': 'Altima', 'weight': 1440},
    {'name': 'GT-R', 'weight': 1765},
    {'name': 'Rogue', 'weight': 1555},
    {'name': '370Z', 'weight': 1460},
    {'name': 'Sentra', 'weight': 1305},
    {'name': 'Murano', 'weight': 1820},
  ],
  'Honda': [
    {'name': 'Civic', 'weight': 1265},
    {'name': 'Accord', 'weight': 1475},
    {'name': 'CR-V', 'weight': 1635},
    {'name': 'Fit', 'weight': 1135},
    {'name': 'Pilot', 'weight': 1965},
    {'name': 'Odyssey', 'weight': 2050},
  ],
  'Chevrolet': [
    {'name': 'Malibu', 'weight': 1475},
    {'name': 'Camaro', 'weight': 1690},
    {'name': 'Silverado', 'weight': 2240},
    {'name': 'Equinox', 'weight': 1610},
    {'name': 'Impala', 'weight': 1660},
    {'name': 'Tahoe', 'weight': 2450},
  ],
  'BMW': [
    {'name': '3 Series', 'weight': 1555},
    {'name': '5 Series', 'weight': 1805},
    {'name': 'X5', 'weight': 2135},
    {'name': 'M3', 'weight': 1680},
    {'name': 'X3', 'weight': 1860},
    {'name': '7 Series', 'weight': 1970},
  ],
  'Mercedes-Benz': [
    {'name': 'C-Class', 'weight': 1540},
    {'name': 'E-Class', 'weight': 1680},
    {'name': 'GLE', 'weight': 2105},
    {'name': 'S-Class', 'weight': 1990},
    {'name': 'GLA', 'weight': 1605},
    {'name': 'GLC', 'weight': 1840},
  ],
  'Hyundai': [
    {'name': 'Elantra', 'weight': 1285},
    {'name': 'Sonata', 'weight': 1480},
    {'name': 'Tucson', 'weight': 1560},
    {'name': 'Santa Fe', 'weight': 1785},
    {'name': 'Kona', 'weight': 1470},
    {'name': 'Palisade', 'weight': 1985},
  ],
  'Kia': [
    {'name': 'Optima', 'weight': 1500},
    {'name': 'Sorento', 'weight': 1770},
    {'name': 'Sportage', 'weight': 1560},
    {'name': 'Stinger', 'weight': 1680},
    {'name': 'Rio', 'weight': 1180},
    {'name': 'Telluride', 'weight': 2000},
  ],
  'Volkswagen': [
    {'name': 'Golf', 'weight': 1350},
    {'name': 'Passat', 'weight': 1485},
    {'name': 'Tiguan', 'weight': 1715},
    {'name': 'Jetta', 'weight': 1320},
    {'name': 'Atlas', 'weight': 1985},
  ],
  'Audi': [
    {'name': 'A3', 'weight': 1420},
    {'name': 'A4', 'weight': 1505},
    {'name': 'Q5', 'weight': 1845},
    {'name': 'Q7', 'weight': 2160},
    {'name': 'R8', 'weight': 1695},
  ],
  'Subaru': [
    {'name': 'Impreza', 'weight': 1370},
    {'name': 'Outback', 'weight': 1690},
    {'name': 'Forester', 'weight': 1580},
    {'name': 'Crosstrek', 'weight': 1505},
    {'name': 'WRX', 'weight': 1565},
  ],
  'Mazda': [
    {'name': 'Mazda3', 'weight': 1320},
    {'name': 'CX-5', 'weight': 1685},
    {'name': 'MX-5 Miata', 'weight': 1135},
    {'name': 'Mazda6', 'weight': 1440},
    {'name': 'CX-9', 'weight': 2005},
  ],
  'Lexus': [
    {'name': 'IS', 'weight': 1700},
    {'name': 'ES', 'weight': 1695},
    {'name': 'RX', 'weight': 1990},
    {'name': 'NX', 'weight': 1755},
    {'name': 'GX', 'weight': 2240},
  ],
  'Jeep': [
    {'name': 'Wrangler', 'weight': 1995},
    {'name': 'Cherokee', 'weight': 1820},
    {'name': 'Grand Cherokee', 'weight': 2185},
    {'name': 'Renegade', 'weight': 1455},
    {'name': 'Compass', 'weight': 1555},
  ],
  'Tesla': [
    {'name': 'Model 3', 'weight': 1750},
    {'name': 'Model S', 'weight': 2100},
    {'name': 'Model X', 'weight': 2460},
    {'name': 'Model Y', 'weight': 1985},
    {'name': 'Cybertruck', 'weight': 2720},
  ],
  'Dodge': [
    {'name': 'Challenger', 'weight': 1770},
    {'name': 'Charger', 'weight': 1965},
    {'name': 'Durango', 'weight': 2225},
    {'name': 'Journey', 'weight': 1845},
    {'name': 'Viper', 'weight': 1515},
  ],
  'Volvo': [
    {'name': 'S60', 'weight': 1660},
    {'name': 'XC40', 'weight': 1775},
    {'name': 'XC60', 'weight': 1980},
    {'name': 'XC90', 'weight': 2190},
    {'name': 'V60', 'weight': 1760},
  ],
  'Porsche': [
    {'name': '911', 'weight': 1475},
    {'name': 'Cayenne', 'weight': 2175},
    {'name': 'Macan', 'weight': 1920},
    {'name': 'Panamera', 'weight': 1995},
    {'name': 'Taycan', 'weight': 2295},
  ],
  'Peugeot': [
    {'name': '208', 'weight': 1065},
    {'name': '3008', 'weight': 1440},
    {'name': '508', 'weight': 1425},
    {'name': '5008', 'weight': 1540},
  ],
  'Renault': [
    {'name': 'Clio', 'weight': 1045},
    {'name': 'Megane', 'weight': 1340},
    {'name': 'Kadjar', 'weight': 1465},
    {'name': 'Captur', 'weight': 1250},
  ],
  'Fiat': [
    {'name': '500', 'weight': 975},
    {'name': 'Panda', 'weight': 960},
    {'name': 'Tipo', 'weight': 1150},
    {'name': '500X', 'weight': 1320},
  ],
  'Citroën': [
    {'name': 'C3', 'weight': 1095},
    {'name': 'C4', 'weight': 1310},
    {'name': 'C5 Aircross', 'weight': 1565},
    {'name': 'Berlingo', 'weight': 1345},
  ],
  'Suzuki': [
    {'name': 'Swift', 'weight': 915},
    {'name': 'Vitara', 'weight': 1180},
    {'name': 'Jimny', 'weight': 1090},
    {'name': 'S-Cross', 'weight': 1245},
  ],
  'Skoda': [
    {'name': 'Octavia', 'weight': 1350},
    {'name': 'Fabia', 'weight': 1060},
    {'name': 'Superb', 'weight': 1510},
    {'name': 'Kodiaq', 'weight': 1650},
  ],
  'Mitsubishi': [
    {'name': 'Outlander', 'weight': 1655},
    {'name': 'Lancer', 'weight': 1335},
    {'name': 'Eclipse Cross', 'weight': 1510},
    {'name': 'Pajero', 'weight': 2120},
  ],
  'Land Rover': [
    {'name': 'Defender', 'weight': 2400},
    {'name': 'Range Rover', 'weight': 2335},
    {'name': 'Discovery', 'weight': 2285},
    {'name': 'Evoque', 'weight': 1755},
  ],
  'Jaguar': [
    {'name': 'XE', 'weight': 1570},
    {'name': 'F-Type', 'weight': 1680},
    {'name': 'XF', 'weight': 1695},
    {'name': 'F-Pace', 'weight': 1980},
  ],
};

final List<String> weatherOptions = [
  'Sunny',
  'Rainy',
  'Snowy',
];
